# Generated by Django 3.1.7 on 2021-06-02 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('net_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Edible',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('flower_type', models.CharField(blank=True, choices=[('I', 'Indica'), ('S', 'Sativa'), ('H', 'Hybrid')], max_length=10, null=True)),
                ('thc_content', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='THC Content (%)')),
                ('cbd_content', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='CBD Content (%)')),
                ('final_test_date', models.DateField()),
                ('package_date', models.DateField()),
                ('harvest_date', models.DateField()),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='PreRoll',
            fields=[
                ('flower_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.flower')),
            ],
            bases=('products.flower',),
        ),
        migrations.CreateModel(
            name='Resin',
            fields=[
                ('flower_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.flower')),
            ],
            bases=('products.flower',),
        ),
        migrations.CreateModel(
            name='Vape',
            fields=[
                ('flower_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.flower')),
            ],
            bases=('products.flower',),
        ),
    ]
