# Generated by Django 3.2.3 on 2021-05-24 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210523_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('flower_type', models.CharField(choices=[('I', 'Indica'), ('S', 'Sativa'), ('H', 'Hybrid')], max_length=10)),
            ],
            bases=('products.product',),
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_width',
        ),
        migrations.CreateModel(
            name='PreRoll',
            fields=[
                ('flower_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.flower')),
            ],
            bases=('products.flower',),
        ),
    ]
