# Generated by Django 3.2.3 on 2021-05-24 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210524_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edible',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('thc_content', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='THC (%)')),
                ('calories', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='Vape',
            fields=[
                ('flower_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.flower')),
            ],
            bases=('products.flower',),
        ),
    ]
