# Generated by Django 3.1.7 on 2021-05-25 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210525_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resin',
            fields=[
                ('flower_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.flower')),
            ],
            bases=('products.flower',),
        ),
        migrations.RemoveField(
            model_name='edible',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='edible',
            name='thc_content',
        ),
        migrations.RemoveField(
            model_name='flower',
            name='thc_content',
        ),
        migrations.AlterField(
            model_name='flower',
            name='flower_type',
            field=models.CharField(blank=True, choices=[('I', 'Indica'), ('S', 'Sativa'), ('H', 'Hybrid')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thc_content', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.flower')),
            ],
        ),
    ]
