# Generated by Django 3.1.7 on 2021-05-26 18:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210525_1613'),
    ]

    operations = [
    ]
